# Generated by Django 5.2.4 on 2025-07-12 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 14, 12, 35, 65228, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
