# Generated by Django 5.2.4 on 2025-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
