# Generated by Django 5.2.1 on 2025-07-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_capacity_course_pre_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='test', help_text='Detailed course content and materials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_type',
            field=models.CharField(choices=[('date', 'Specific Date'), ('weekday', 'Weekly Schedule')], default='date', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
