# Generated by Django 5.2.1 on 2025-07-31 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_date_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Course price in USD', max_digits=10),
        ),
    ]
