# Generated by Django 5.2.1 on 2025-08-01 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='specific_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weekday',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('date', 'Specific Date'), ('weekday', 'Weekly Schedule')], default='date', max_length=7)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='course.course')),
            ],
        ),
    ]
