# Generated by Django 5.2.1 on 2025-08-01 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, help_text='Grade must be between 0 and 20', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0, message='Grade cannot be less than 0'), django.core.validators.MaxValueValidator(20.0, message='Grade cannot be more than 20')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.enrollment')),
            ],
            options={
                'unique_together': {('enrollment',)},
            },
        ),
    ]
